services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: "composer install --no-dev && php artisan config:cache"
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      # Add your actual DB config here or set in Render UI
